#!/usr/bin/env python3
"""Install shell wrappers and connect this checkout to Bash or Zsh."""

import argparse
import os
import shlex
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent
FILES = (
    'launch.py',
    'footer.py',
    'claude_status.py',
    'tmux.conf',
    'settings.example.json',
    'README.md',
    'LICENSE',
)
REQUIRED_COMMANDS = ('tmux', 'git', 'lsof')
SUPPORTED_SHELLS = ('bash', 'zsh')
BEGIN_MARKER = '# >>> harness-footer >>>'
END_MARKER = '# <<< harness-footer <<<'
LEGACY_BEGIN_MARKER = '# >>> agent-tmux >>>'
LEGACY_END_MARKER = '# <<< agent-tmux <<<'


def install(prefix=None):
    """Write the wrapper scripts and return (target, wrapper, activation).

    By default the checkout is the installation, so git updates apply
    immediately. A prefix installs a separate runtime copy instead.
    """
    if prefix is None:
        target, bin_dir = ROOT, ROOT / 'bin'
    else:
        prefix = Path(prefix).expanduser().resolve()
        target, bin_dir = prefix / 'share' / 'harness-footer', prefix / 'bin'
    target.mkdir(parents=True, exist_ok=True)
    bin_dir.mkdir(parents=True, exist_ok=True)
    if target != ROOT:
        for name in FILES:
            shutil.copy2(ROOT / name, target / name)

    settings = target / 'settings.json'
    if not settings.exists():
        shutil.copy2(target / 'settings.example.json', settings)

    launcher = shlex.join([sys.executable, str(target / 'launch.py')])
    wrapper = bin_dir / 'harness-footer'
    wrapper.write_text(f'#!/bin/sh\nexec {launcher} "$@"\n')
    wrapper.chmod(0o755)
    activation = target / 'activate.sh'
    activation.write_text(
        '# Generated by harness-footer. Source from Bash or Zsh.\n'
        f'codex() {{ {launcher} codex "$@"; }}\n'
        f'claude() {{ {launcher} claude "$@"; }}\n'
    )
    return target, wrapper, activation


def replace_marked_block(text, block, shell_rc):
    text = text.replace(LEGACY_BEGIN_MARKER, BEGIN_MARKER)
    text = text.replace(LEGACY_END_MARKER, END_MARKER)
    if BEGIN_MARKER not in text and END_MARKER not in text:
        separator = '\n' if text and not text.endswith('\n') else ''
        return f'{text}{separator}\n{block}'

    well_formed = (
        text.count(BEGIN_MARKER) == 1
        and text.count(END_MARKER) == 1
        and text.index(BEGIN_MARKER) < text.index(END_MARKER)
    )
    if not well_formed:
        raise ValueError(
            f'Malformed harness-footer block in {shell_rc}; '
            'repair it before installing.'
        )
    start = text.index(BEGIN_MARKER)
    end = text.index(END_MARKER) + len(END_MARKER)
    if text.startswith('\n', end):
        end += 1
    return text[:start] + block + text[end:]


def backup_path(shell_rc):
    stamp = datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%S%fZ')
    return shell_rc.with_name(f'{shell_rc.name}.harness-footer-{stamp}.bak')


def connect_shell(activation, shell_rc):
    """Source activation from shell_rc; return (shell_rc, backup or None)."""
    shell_rc = Path(shell_rc).expanduser().resolve()
    current = shell_rc.read_text() if shell_rc.exists() else ''
    block = f'{BEGIN_MARKER}\n. {shlex.quote(str(activation))}\n{END_MARKER}\n'
    updated = replace_marked_block(current, block, shell_rc)
    if updated == current:
        return shell_rc, None

    backup = None
    shell_rc.parent.mkdir(parents=True, exist_ok=True)
    if shell_rc.exists():
        backup = backup_path(shell_rc)
        shutil.copy2(shell_rc, backup)
    shell_rc.write_text(updated)
    return shell_rc, backup


def default_shell_rc(shell):
    if shell == 'zsh':
        return Path(os.environ.get('ZDOTDIR') or Path.home()) / '.zshrc'
    return Path.home() / '.bashrc'


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        '--prefix',
        type=Path,
        help='Install a separate copy here (default: use this checkout)',
    )
    parser.add_argument(
        '--shell',
        choices=SUPPORTED_SHELLS,
        default=Path(os.environ.get('SHELL', '/bin/zsh')).name,
        help='Shell to configure: bash or zsh (default: $SHELL)',
    )
    parser.add_argument(
        '--shell-rc',
        type=Path,
        help='Override the shell startup file to update',
    )
    parser.add_argument(
        '--no-shell',
        action='store_true',
        help='Generate wrappers without editing a startup file',
    )
    args = parser.parse_args()
    if sys.version_info < (3, 10):  # noqa: UP036 - reached by older Pythons.
        parser.error('Python 3.10 or later is required')
    if sys.platform not in ('darwin', 'linux'):
        parser.error('Supported platforms: macOS and Linux (including WSL)')
    missing = [name for name in REQUIRED_COMMANDS if not shutil.which(name)]
    if missing:
        parser.error(
            'Install missing dependencies first: ' + ', '.join(missing)
        )
    if args.shell not in SUPPORTED_SHELLS and not args.no_shell:
        parser.error('Select --shell bash or --shell zsh')
    return args


def main():
    args = parse_args()
    target, wrapper, activation = install(args.prefix)
    print(f'Installed: {target}\nCommand: {wrapper}')
    if not args.no_shell:
        shell_rc = args.shell_rc or default_shell_rc(args.shell)
        shell_rc, backup = connect_shell(activation, shell_rc)
        print(f'Connected: {shell_rc}')
        if backup:
            print(f'Backup: {backup}')
    print('\nOpen a new shell, or activate in the current one:')
    print(f'. {shlex.quote(str(activation))}')
    print(f'\nCustomize: {target / "settings.json"}')
    print(
        'Re-running is safe: existing settings are preserved and the shell '
        'block is updated in place.'
    )


if __name__ == '__main__':
    main()
