#!/usr/bin/env python3
"""Install shell wrappers and connect this checkout to Bash or Zsh."""
import argparse
from datetime import datetime, timezone
import os
from pathlib import Path
import shlex
import shutil
import sys

ROOT = Path(__file__).resolve().parent
FILES = ('launch.py', 'footer.py', 'claude_status.py', 'tmux.conf',
         'settings.example.json', 'README.md', 'LICENSE')
BEGIN = '# >>> harness-footer >>>'
END = '# <<< harness-footer <<<'


def install(prefix=None):
    # The default keeps the checkout itself as the installation, so git updates
    # immediately apply. --prefix optionally installs a separate runtime copy.
    prefix = Path(prefix).expanduser().resolve() if prefix is not None else None
    target = prefix / 'share' / 'harness-footer' if prefix else ROOT
    bin_dir = prefix / 'bin' if prefix else ROOT / 'bin'
    target.mkdir(parents=True, exist_ok=True)
    bin_dir.mkdir(parents=True, exist_ok=True)
    if target != ROOT:
        for name in FILES:
            shutil.copy2(ROOT / name, target / name)
    settings = target / 'settings.json'
    if not settings.exists():
        shutil.copy2(target / 'settings.example.json', settings)
    command = shlex.join([sys.executable, str(target / 'launch.py')])
    wrapper = bin_dir / 'harness-footer'
    wrapper.write_text('#!/bin/sh\nexec ' + command + ' "$@"\n')
    wrapper.chmod(0o755)
    activation = target / 'activate.sh'
    activation.write_text(
        '# Generated by harness-footer. Source from Bash or Zsh.\n'
        'codex() { ' + command + ' codex "$@"; }\n'
        'claude() { ' + command + ' claude "$@"; }\n'
    )
    return target, wrapper, activation


def connect_shell(activation, shell_rc):
    shell_rc = Path(shell_rc).expanduser().resolve()
    before = shell_rc.read_text() if shell_rc.exists() else ''
    original = before
    # Upgrade the original project name without leaving two activation blocks.
    before = before.replace('# >>> agent-tmux >>>', BEGIN).replace('# <<< agent-tmux <<<', END)
    block = BEGIN + '\n. ' + shlex.quote(str(activation)) + '\n' + END + '\n'
    if BEGIN in before or END in before:
        if before.count(BEGIN) != 1 or before.count(END) != 1 or before.index(END) < before.index(BEGIN):
            raise ValueError(f'Malformed harness-footer block in {shell_rc}; repair it before installing.')
        start = before.index(BEGIN)
        end = before.index(END) + len(END)
        if before[end:end + 1] == '\n':
            end += 1
        after = before[:start] + block + before[end:]
    else:
        after = before + ('\n' if before and not before.endswith('\n') else '') + '\n' + block
    backup = None
    if original != after:
        shell_rc.parent.mkdir(parents=True, exist_ok=True)
        if shell_rc.exists():
            stamp = datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%S%fZ')
            backup = shell_rc.with_name(shell_rc.name + '.harness-footer-' + stamp + '.bak')
            shutil.copy2(shell_rc, backup)
        shell_rc.write_text(after)
    return shell_rc, backup


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--prefix', type=Path,
                        help='Optional separate installation prefix; default: use this checkout')
    parser.add_argument('--shell', choices=['bash', 'zsh'],
                        default=Path(os.environ.get('SHELL', '/bin/zsh')).name,
                        help='Shell to configure (default: $SHELL)')
    parser.add_argument('--shell-rc', type=Path, help='Override the shell startup file to update')
    parser.add_argument('--no-shell', action='store_true', help='Generate wrappers without editing a startup file')
    args = parser.parse_args()
    if sys.version_info < (3, 10):
        parser.error('Python 3.10 or later is required')
    if sys.platform not in ('darwin', 'linux'):
        parser.error('Supported platforms: macOS and Linux (including WSL)')
    missing = [name for name in ('tmux', 'git', 'lsof') if not shutil.which(name)]
    if missing:
        parser.error('Install missing dependencies first: ' + ', '.join(missing))
    if args.shell not in ('bash', 'zsh'):
        parser.error('Select --shell bash or --shell zsh')
    target, wrapper, activation = install(args.prefix)
    print(f'Installed: {target}\nCommand: {wrapper}')
    if not args.no_shell:
        shell_rc = args.shell_rc or (
            Path(os.environ.get('ZDOTDIR') or str(Path.home())) / '.zshrc'
            if args.shell == 'zsh' else Path.home() / '.bashrc')
        shell_rc, backup = connect_shell(activation, shell_rc)
        print(f'Connected: {shell_rc}')
        if backup:
            print(f'Backup: {backup}')
    print('\nOpen a new shell, or activate in the current one:')
    print('. ' + shlex.quote(str(activation)))
    print(f'\nCustomize: {target / "settings.json"}')
    print('Re-running is safe: existing settings are preserved and the shell block is updated in place.')


if __name__ == '__main__':
    main()
